### ISSUE TITLE
misaligned furigana and text selection

### ISSUE THREAD

**Issue by IdleUnit** [ttu-ttu/ebook-reader#247] opened 2023-07-27 07:23 UTC
became like this all of a sudden
![Screenshot 2023-07-27 at 10-20-50 ッツ Ebook Reader](https://github.com/ttu-ttu/ebook-reader/assets/110023215/226aee0a-a499-4691-bf0d-d6737ed39076)

**Comment by Renji-XD** [comment] 2023-07-27 08:14
hi,

is that the case for all your books and what browser / domain are you using?

i tried multiple files and fonts and can't reproduce such a behavior on my end.

Maybe you could try out a different font or check the old domain https://ttu-ebook.web.app/manage (assuming you are using the current one)

If it works on a temporary clean browser profile you could probably also export your data, wipe the site settings and reimport. But if it still not works i would need to monitor for other people having the same issue as i can't reproduce and therefore not really comment on it

**Comment by Wren6991** [comment] 2023-07-27 08:25
Same for me, Firefox 115.0.2 on Ubuntu. Started happening when I refreshed the page, so probably something that changed in the last day or two. I don't see this behaviour using the old site, and all of my books with furigana show this issue. I'm using the default font, Noto JP

**Comment by IdleUnit** [comment] 2023-07-27 09:06
Same for all books. Firefox 115.0.2 on manjaro is what I'm using, Noto Serif JP is the font I used. Had it typed in the options manually and after deleting it (it's the default font apparently and I assume the one I was using was of an older version or something, no clue) the furigana part is fixed, not the selection one though. Some other fonts have either of the two problems as well, others don't.
The old domain works perfectly, thanks for pointing it out.

**Comment by Renji-XD** [comment] 2023-07-27 10:39
There was a change to the font files - i reverted them back for a test. Please do a couple of tab refreshes (or hard reloads via ctrl+f5) and check if it behaves as you before (maybe take up to 1h for cdn cache burst)

**Comment by ChaseOxide** [comment] 2023-07-27 11:12
Update: It should be possible now to retrieve the latest font files (i.e. the fix) without a hard refresh

**Comment by KojoZero** [comment] 2023-07-27 16:20
@Renji-XD Ok, I'll try looking into the issue and if I'm able to fix it, I'll try pushing again.

**Comment by Renji-XD** [comment] 2023-07-28 22:53
@IdleUnit @Wren6991 There were new versions for the fonts pushed - looked fine on the book i used for testing before.
Could you check on your side - if the feedback is fine i would probably also close this issue

**Comment by IdleUnit** [comment] 2023-07-29 05:44
@Renji-XD back to normal for me ever since yesterday
thanks for your hard work guys

**Closed** 2023-07-29 12:21 UTC
Labels: bug
