### ISSUE TITLE
yomichan popup window + settings not showing up properly on mobile

### ISSUE THREAD

**Issue by Astarka06** [ttu-ttu/ebook-reader#27] opened 2021-11-14 01:34 UTC
I've been trying to read epubs on mobile using kiwi browser + yomichan. The popup window shows up out of frame(?) usually all the way to the left, meaning I can see the corner of it but not really what's written in it. Also the fullscreen button doesn't show up either which makes me assume it's all the way to the left. When I click settings it also seems to be showing up to the left too where I can't see it. Yomichan works perfectly on other websites, only gets funny with this ebook reader. 
I'm currently using a Samsung Galaxy A02s, do you guys think it's the phone's problem?
![Screenshot_20211113-223606_Kiwi Browser](https://user-images.githubusercontent.com/72636452/141664382-b762a23a-ef44-47b5-a1cd-0a6581614ad1.jpg)
![Screenshot_20211113-223553_Kiwi Browser](https://user-images.githubusercontent.com/72636452/141664387-4648b280-6d89-45cb-b5cb-1e728dab9847.jpg)

**Comment by ttu-ttu** [comment] 2021-11-14 02:09
Are you on "PC View"? Try turning it off if you are

**Comment by Astarka06** [comment] 2021-11-14 02:13
> Are you on "PC View"? Try turning it off if you are

You mean "desktop mode"? I've been trying to make it work on desktop mode and the normal mobile mode and the same thing happens to both of them.

**Comment by ttu-ttu** [comment] 2021-11-14 02:46
For me I can't reproduce the UI as shown in your screenshot unless I turn on "Desktop site," and at the moment I don't think I can fix "Desktop site" view on an Android device, which is why I suggest to turn it off.

If the UI still goes off screen even if you turn off "Desktop site," it's likely something very specific for your case, and I don't know how to fix it. Alternatively you can try on other readers, or [jidoujisho](https://github.com/lrorpilla/jidoujisho) which embeds this reader in their app.

**Comment by Astarka06** [comment] 2021-11-14 16:04
> or [jidoujisho](https://github.com/lrorpilla/jidoujisho) which embeds this reader in their app.

i`ll use that. It won`t turn into normal mobile mode so I guess it can`t be helped. Thank you for your attention, man.

**Comment by ttu-ttu** [comment] 2021-12-28 16:01
Closed as it's not reproducible

**Closed by ttu-ttu** 2021-12-28 16:01 UTC
