### ISSUE TITLE
Highlight sentences and make notes for the highlights [Feature Request]

### ISSUE THREAD

**Issue by AdriGrana** [ttu-ttu/ebook-reader#390] opened 2024-10-24 20:07 UTC
Title says it all, I think this would be  really useful to highlight sentences and make notes according to the highlights. I often want to leave some short note where I explain the context so when I get back into reading another day don't have to reread what happened. It's a basic feature pretty much all pdf readers, ebook readers and ebooks have, so I think tsu should have it too.

**Comment by Renji-XD** [comment] 2024-10-25 08:37
hi, ty for your suggestion. i will close this as duplicate of #21 (which would also includes notes etc.) which can be tracked

**Closed by Renji-XD** 2024-10-25 08:37 UTC
