### ISSUE TITLE
Clearing History & Cookies Loses Book Progres

### ISSUE THREAD

**Issue by aramrw** [ttu-ttu/ebook-reader#343] opened 2024-07-04 19:57 UTC
I have my book data saved to Google Drive, however I cleared my history & cookies and now my book got reset 0% and I lost where I was at...

Also I thought I would also mention that data differs between browsers & mobile as well _(I tested it with Chrome, Edge, and Arc browsers)_ which I'm guessing is also the reason why I lost my progress after clearing my history.

Edit: Also it looks like all my settings got cleared as well, including my stats...

`Google Chrome v126.0.6478.127 (Official Build) (64bit)`

**Comment by Renji-XD** [comment] 2024-07-04 20:40
hi,

not 100% sure what you want to report / what response you expect so just let me comment on your points

- Clearing Data: As described in the readme the data is stored locally in the browser. It counts as "other site data" which also gets deleted with the respective option so clearing the whole browser data leads to a wipe of everything as expected

- As you said yourself - with the wipe you cleared also your settings. so you probably did not re enabled the sync or have not re enabled gdrive as sync target. Then you probably reloaded the book locally or opened an old version which created a fresh entry with more recent timestamps which therefore overwrote the data after reenabling the sync. 

Gdrive keeps some file versions (right click ->  FileInformation) so the only suggestion i can give is to go through them and checking via online editor/text editor if the progress value looks right to you and then to restore that version. I am not 100% sure if manually replaced files can be seen from the app tbh but one way which should work is to delete the local data in your browser and do a zipped import (see readme) from the data stored on gdrive. You can do a zip export from local data first to see how the expected structure looks like. Temporarily enabling overwrite/replace options in settings could help - afterwards you can sync up your local imported data back to gdrive and everything should be restored

- for inconsistencies between browsers i can just repeat the previous points. Maybe you haven't enabled the up/down auto export options and/or choosen a sync target in one of them.. on my side i can't see any unexpected behavior so i would need more informations / steps to reproduce if there is really an issue which nobody else reported yet

**Comment by aramrw** [comment] 2024-07-04 20:56
> As you said yourself - with the wipe you cleared also your settings. so you probably did not re enabled the sync or have not re enabled gdrive as sync target. Then you probably reloaded the book locally or opened an old version which created a fresh entry with more recent timestamps which therefore overwrote the data after reenabling the sync.
> 

You were right, I didn't have auto import & export set. 

1. I set `Auto Import & Export` to `All`.
2. Set `ttu-gdrive-default` as `sync target`. 

Now, it _does_ show the correct location _(red bar at the bottom of the cover of the book)_, however if I actually go back into the book, I am back on the first page. 

If you want I can recreate these steps again and record a video?

**Comment by Renji-XD** [comment] 2024-07-04 21:01
if you are talking about a position between images then i guess it is not supported because the progress only works on text.

try to scroll to some location where the counter in the right corner bottom has changed and set a boomark. then you can trigger a manual sync by clicking on that cloud icon in the left bottom corner. If you now refresh the page you should still be there and if you refresh it on an other browser (remember - going to manager will do a new bookmark, so just f5 or whatever) you should also land somewhere close there

**Comment by aramrw** [comment] 2024-07-04 21:42
> try to scroll to some location where the counter in the right corner bottom has changed and set a boomark. then you can trigger a manual sync by clicking on that cloud icon in the left bottom corner.
>

You can see the red line _(when selecting the book)_ is at the correct spot so the data _is_ loading _(i believe so right???)_ But it starts me back at the beginning? I tried reloading, waiting, nothing, always at page 1.
Am I still doing something wrong? 

https://github.com/ttu-ttu/ebook-reader/assets/106574385/dcb9c267-2306-48e5-9022-bfe3411bfff7

**Comment by Renji-XD** [comment] 2024-07-04 22:28
no that looks fine - and the same exact steps also seems to work on my site. i guess the only "interesting" difference to my previous test was that you read from the external storage and not synced it down before. But both ways seems to be fine on my side.

i guess what you could check and share is:
- after syncing is there a a file on gdrive and is the value for the progress inside the file also not 0 but something like 0.078...
- after deleting the data and before opening the book open the developer tools (f12) then open the book and wait until it loaded. then on console tab check if there is any error printed out, switch to network tab and check if any of the requests failed, switch to application, indexeddb (left under storage) => books => bookmark.

**Comment by aramrw** [comment] 2024-07-04 22:53
### Before clearing cookies
`progress_1_6_1720132283555_0.7190132654344272.json`
```
{
  "dataId": 1,
  "exploredCharCount": 91493,
  "progress": 0.7190132654344272, 
  "lastBookmarkModified": 1720132283555
}
```
### After clearing cookies: 
`progress_1_6_1720132283555_0.7190132654344272.json`'s values are the exact same in Google Drive.

### Errors: 
_I have no sort of ad block installed or any extensions that aren't local_.
```
▼ Cross-Origin-Opener-Policy policy would block the window.closed call.
    clearAuthData @ store.o6di8xEP.js
```
 _(**x2**)_.
 
All network requests to `googleapis` return 200.
No entries exist in the `bookmark` store.

**Comment by Renji-XD** [comment] 2024-07-04 23:02
have you tested this time at 91493 character position (just asking as the video was at 10k)?

the network request with "fields=files(id,name,thumbnailLink,parents)" in the url - when you check the response. does it have the progress file in the file list?

Also just to double check - an entry for the book under the data item exists or not?

**Comment by aramrw** [comment] 2024-07-04 23:25
> have you tested this time at 91493 character position (just asking as the video was at 10k)?
>
Yes the Google Drive data is correctly being exported 
> the network request with "fields=files(id,name,thumbnailLink,parents)" in the url - when you check the response. does it have the progress file in the file list?
>
_googleapis.com/drive/v3/files?corpora=user&spaces=drive&fields=files%28id%2Cname%29%2CnextPageToken&q=trashed%3Dfalse+and+mimeType%3D%27application%2Fvnd.google-apps.folder%27+and+%271ed6JHl-eseC3VXBz0OR8LSXP3TVTvRFE%27+in+parents_
```
{
  "files": [
    {
      "id": "1jshXA5ArsXCL0eL3_Vors2mkjtcF-ygx",
      "name": "恥知らずのパープルヘイズ―ジョジョの奇妙な冒険より―"
    }
  ]
}
```
_googleapis.com/drive/v3/files?corpora=user&spaces=drive&fields=files%28id%2Cname%2CthumbnailLink%2Cparents%29%2CnextPageToken&q=trashed%3Dfalse+and+%28%271jshXA5ArsXCL0eL3_Vors2mkjtcF-ygx%27+in+parents%29P_
```
{
  "files": [
    {
      "parents": [
        "1jshXA5ArsXCL0eL3_Vors2mkjtcF-ygx"
      ],
      "id": "16hAzRQFpwBmBP22OSegI_55HLOTKh5yG",
      "name": "progress_1_6_1720132524359_0.7190132654344272.json"
    },
    {
      "parents": [
        "1jshXA5ArsXCL0eL3_Vors2mkjtcF-ygx"
      ],
      "id": "1zGTnAKACwqIwd9E6VpzHBz0v8ve_rd5o",
      "name": "bookdata_1_6_73456_1715750629182_1720132517073.zip"
    },
    {
      "parents": [
        "1jshXA5ArsXCL0eL3_Vors2mkjtcF-ygx"
      ],
      "thumbnailLink": "https://lh3.googleusercontent.com/drive-storage/AJQWtBN9ltmDtmkpTWDlalMu83MWbEj_8oMJdWGBMZ77w9j3EK6022H4LPbY0rZYBMjqG9T30lLvoBZOzIMe-mLFZbcTlfTyu1YoySV8JyfZCWjtom0=s220",
      "id": "1puNPG1U2PxZM_AHXRLU5NCqsLyO46T-2",
      "name": "cover_1_5.jpeg"
    }
  ]
}
```
> Also just to double check - an entry for the book under the data item exists or not and does it have "ttu-gdrive-default" as storageSource value?
>
So you mean `IndexedDB`/`books`/**`data`**/`item`? Every store  inside IndexedDB _(audioBook, bookmark, handle, lastItem etc)_ is empty

**Comment by Renji-XD** [comment] 2024-07-04 23:34
it is IndexedDB/books/data/ => it was also more rethorical because this has to exist technically.. otherwise the reader would just jump back to the manager. so try to open the devtools after the book was loaded and then check the indexeddb (network / console we should have covered). 

Whole thing is very strange cause everything left should be in error handlers which would popup an error dialog.. so right now my assumption is the indexeddb view was not refreshed and you have the data but for whatever reason it does not scroll (which is probably not further debugable in this way i am afraid)

**Comment by aramrw** [comment] 2024-07-04 23:53
> Whole thing is very strange cause everything left should be in error handlers which would popup an error dialog.. so right now my assumption is the indexeddb view was not refreshed and you have the data but for whatever reason it does not scroll (which is probably not further debugable in this way i am afraid)
>
Alright. I appreciate the help, for me it's actually not a big deal I just wanted to see what was up with it 👍🏼 

I will do more tests on other browsers/another pc/my phone later
If I find anything I'll let you know

**Comment by Renji-XD** [comment] 2024-07-05 00:09
sure - you could also "just for fun" test out if syncing the book itself to the browser and then opening from browser view aka locally will sync the other data probably .. maybe that works for you

**Comment by Renji-XD** [comment] 2024-10-05 11:55
as discussed there is probably no real way to debug further and it doesn't seem to be a global issue - therefore i will close this issue for now. feel free to open a new one in case you have updates or other information to check

**Closed by Renji-XD** 2024-10-05 11:55 UTC
