### ISSUE TITLE
An Error occured: Failed to read large IndexedDB value

### ISSUE THREAD

**Issue by kimjongbing** [ttu-ttu/ebook-reader#265] opened 2023-09-13 12:35 UTC
so i have my light novels on my mac and i read it from there, when i open a specific book it will open normally. but when i exit at https://reader.ttsu.app/manage the books not there and it has "Failure
An Error occured: Failed to read large IndexedDB value". 

`{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
  "viewport": {
    "visualViewport": true,
    "width": 1920,
    "height": 955
  },
  "settings": {
    "theme": "light-theme",
    "viewMode": "paginated",
    "fontFamilyGroupOne": "",
    "fontFamilyGroupTwo": "",
    "fontSize": 20,
    "lineHeight": 1.65,
    "firstDimensionMargin": 0,
    "secondDimensionMaxValue": 0,
    "swipeThreshold": 10,
    "disableWheelNavigation": false,
    "writingMode": "vertical-rl",
    "confirmClose": false,
    "autoBookmark": false,
    "hideSpoilerImage": true,
    "hideFurigana": false,
    "furiganaStyle": "partial",
    "avoidPageBreak": false,
    "customReadingPointEnabled": false,
    "selectionToBookmarkEnabled": false,
    "pageColumns": 0,
    "autoPositionOnResize": true,
    "requestPersistentStorage": true,
    "cacheStorageData": true,
    "autoReplication": "down",
    "replicationSaveBehavior": "new",
    "showExternalPlaceholder": false,
    "gDriveStorageSource": false,
    "oneDriveStorageSource": true,
    "fsStorageSource": false,
    "syncTarget": true,
    "isOnline": true,
    "multiplier": 20
  },
  "log": [
    {
      "level": 4,
      "args": [
        "Failed to read large IndexedDB value"
      ]
    }
  ]
}`

**Comment by Renji-XD** [comment] 2023-09-13 20:12
hi,
as far i understood it occurs in general/with all books - so sounds unfortunately like an system specific issue which is probably really hard to debug on dev side. Also the *-OS Platform seems to be in general quite iffy when it comes to storing and reading large data often...

I leave this issue open for the time being but for now i can only share some ideas you may could try out as it sounds that your local db may got corrupted or similar:

1) Check your Storage on which your Browser Profile is stored in terms of capacity - if its low maybe try to move some data temporarily in conjunction with one of the next options
2) Try to clean the Website Storage - that will all Data and rebuild everything from scratch which may helps. In Chrome it is e. g. in the Developer Tools => Application => Storage
![image](https://github.com/ttu-ttu/ebook-reader/assets/6409827/956313d4-aa41-46e3-b9be-0282ccdbe628)
3) Alternatively/On Top try out a new temporary Profile without Extensions to ensure the root cause is not inside your current Profile

**Comment by kimjongbing** [comment] 2023-09-14 02:49
Step 2 in your instructions (clean website storage) solved my problem. Thank you.

**Comment by Renji-XD** [comment] 2023-09-14 07:33
Sounds good - as there is no direct work related i will close this issue for now (keeping the error in mind whenever i should encounter it for further analysis)

**Closed by Renji-XD** 2023-09-14 07:33 UTC
